language: node_js
node_js:
  - "6"
  - "5"
  - "4"

env:
  - CXX=clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - g++-4.8
      - llvm-3.6
      - libstdc++-4.9-dev
      - llvm-3.6-dev
      - clang-3.6

compiler: clang

sudo: required

os:
  - linux
  - os: osx

osx_image: xcode7.2

before_install:
  - export TSD_GITHUB_TOKEN=8591f447276e1caa1b9636b9c8053d768130464f
  - node --version
  - npm --version
  - gcc --version
  - sudo apt-get update
  - sudo apt-get -y install softhsm
  - /usr/bin/softhsm-util --init-token --slot 0 --label "My token 1"

script:
  - npm install
  - npm test

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules
